workflows:
  android-release:
    name: Android Release Workflow
    max_build_duration: 60
    environment:
      java: 17
    scripts:
      - name: Generate Gradle Wrapper
        script: |
          # Install Gradle CLI (available in Codemagic)
          gradle --version
          # Generate wrapper with Gradle 8.0
          gradle wrapper --gradle-version 8.0
          chmod +x ./gradlew

      - name: Build Debug APK (signed & installable)
        script: |
          ./gradlew clean assembleDebug

      - name: List APK
        script: |
          ls -la app/build/outputs/apk/debug/

    artifacts:
      - app/build/outputs/**/*.apk
